### ISSUE TITLE
Maintainers wanted

### ISSUE THREAD

**Issue by klaascuvelier** [jlmakes/karma-rollup-preprocessor#14]
We're not actively using this plugin anymore (as you might be able to see from the pulse), so we're looking for some new maintainers who could give this project the love it needs.

[![Maintainers Wanted](https://img.shields.io/badge/maintainers-wanted-red.svg)](https://github.com/pickhardt/maintainers-wanted)

**Comment by jlmakes** [comment]
I just spent 3 days struggling to integrate Rollup into Karma @klaascuvelier, and @brianmhunt's PR fixed my issues.

I would be willing to take over to fix things up so no one else has to suffer the same frustration.

**Comment by jlmakes** [comment]
Any updates on this @klaascuvelier?

I just spent 3 frustrating days integrating Rollup into Karma, and I'd be willing to carry the torch for a while to prevent similar frustration for others.

**Comment by klaascuvelier** [comment]
No updates, nobody volunteered until you just did.
I can transfer you the ownership right away if you want.

**Comment by jlmakes** [comment]
Let's do it, I'll do what I can!

**Comment by jlmakes** [comment]
Let's do it @klaascuvelier!

My handle is **jlmakes** on both NPM and GitHub.

**Comment by klaascuvelier** [comment]
I'm afk right now, will follow up asap

**Comment by klaascuvelier** [comment]
I sent you a request for the ownership on Github and added you as owner on npm.
Thanks for taking this up @jlmakes, as we didn't use the library ourselves anymore, we could not invest time in the maintenance and development

**Comment by jlmakes** [comment]
I think the Rollup bundler is the best solution for browser libraries until ES6 imports are natively supported across devices/browsers... and being able to test the same bundles you're distributing is essential.

I use both Rollup and Karma on an important personal/open source project, so I will do my best. Thanks for passing the torch @klaascuvelier!
