### ISSUE TITLE
Watch doesn't work reliably

### ISSUE THREAD

**Issue by FezVrasta** [jlmakes/karma-rollup-preprocessor#17]
Hi, first, thanks for maintaining this plugin!

I'm on `3.0.2` and Node 7, and I have a problem with the watch feature.
This is my karma configuration:

```js
autoWatch: true,
preprocessors: {
    [`${root}/src/**/*.js`]: ['rollup'],
    [`${root}/tests/**/*.js`]: ['rollup'],
},
rollupPreprocessor: {
    moduleName: 'test',
    exports: 'named',
    format: 'umd',
    sourceMap: 'inline',
    plugins: [babel({
        presets: [
            ['es2015', { modules: false }],
            'stage-2',
        ],
    })],
},
files: [
    { pattern:`${root}/src/**/*.js`, included: false, watched: true },
    `${root}/tests/styles/*.css`,
    `${root}/tests/functional/*.js`,
    `${root}/tests/unit/*.js`,
],
```

Describing how my tests work, the test files `import` the source files of my library and rollup takes care to compile everything.

The problem is that if I change a file in my tests, the watch task works, if instead I change a file of the source of my library, the bundle isn't updated.

Am I doing something wrong? Sometimes it works, sometimes not... randomly.

**Comment by FezVrasta** [comment]
Or better, sometimes it works, sometimes not.. Randomly.

**Comment by jlmakes** [comment]
What version of the library are you using?

**Comment by jlmakes** [comment]
What version of the library are you using?
Sounds very similar to #3, which was solved in `v3.0.0`.

I'm actually working on a better solution, since relying on Karma's watch seems to be a limitation; it seems `karma-webpack` uses its own watch for similar reasons.

**Comment by FezVrasta** [comment]
I'm on 3.0.2 and Node 7

**Comment by jlmakes** [comment]
Issue #3 dealt with a very similar problem, and had a decent solution for `v3.0.0`...

Which files are not triggering a new bundle?
If you can put together a simple repository demonstrating the problem, I will be able much better equipped to release a fix.

**Comment by FezVrasta** [comment]
Seems to happen randomly on the same exact files. I'm experiencing it in https://github.com/FezVrasta/popper.js/tree/v1-dev

This is the config:
https://github.com/FezVrasta/popper.js/blob/v1-dev/scripts/karma.conf.js#L52-L73

**Comment by jlmakes** [comment]
Your popper package is not really a simple/isolated example of the problem.

Does the problem occur with any of the files in your `files` array, or with specific ones?
Have you looked at the `DEBUG_INFO` output?

**Comment by FezVrasta** [comment]
It occur with one of the files in the files array (actually, lot of them, all?).

I have not looked at the debug info, I'll take a look when I have a minute.

**Comment by jlmakes** [comment]
I'm dropping support for Node `0.12` and releasing `karma-rollup-proprocessor@4.0.0` soon. Since relying on Karma's watcher seems limiting, I'm also working on handling watch internally (and simply notifying karma when files have changed).

If you have in fact uncovered a bug here, I want to make sure that the new solution solves it. Would you be willing to help me test the new release @FezVrasta?

**Comment by FezVrasta** [comment]
sure

**Comment by jlmakes** [comment]
Alright well it'll take a bit though, I'm working on a few open source projects. I think we should still see what we can figure out using `3.0.2`, and when `4.0.0` is ready you can drop that into your project to help test.

**Comment by FezVrasta** [comment]
no problem, it's just a bit annoying, nothing critical

**Comment by menangen** [comment]
I too have troubles with Karma and rollup + Vue.js components, Karma config has
``` javascript
files: [
        'browser/src/tests/global.spec.js',
        {pattern: 'browser/src/components/*.vue', served: false, included: false}
    ],
preprocessors: {
        'browser/src/tests/global.spec.js': ['rollup']
    },
```
In _global.spec.js_ I have:
``` javascript
import Vue from 'vue'

import helloTemplate from 'components/hello.vue'
import vueTemplate from 'components/test.vue'

describe('Vue components', function() {

    it('has a dummy Vue.js test', () => {

        const vm = new Vue({
            el: document.createElement('div'),
            render: (createElement) => createElement(helloTemplate)
        });

        expect(vm.$el.querySelector('h1').textContent).toBe('Welcome to Vue.js App')
    });

    it('has second Vue.js test', () => {

        const vm = new Vue({
            el: document.createElement('div'),
            render: (createElement) => createElement(vueTemplate)
        });

        expect(vm.$el.querySelector('h1').textContent).toBe('hello')
    });
});
```
So, in compiled _global.spec.js_ I have all bundled Vue.js library + vue components and tests specs, but when I change one of vue component - rollup does not recompile all dependencies such as .vue single file components imported in _global.spec.js_. Tests can failed or success done only if I write changes in main _global.spec.js_, not in components.

So, we have to know how to rebuild rollup cache on file changes.

In my Karma v1.3.0 server logs on dep. changes:

```bash
10 01 2017 19:34:34.179:INFO [watcher]: Changed file "/Users/menangen/WebStormProjects/game-vue-nodejs-site/browser/src/components/test.vue".
10 01 2017 19:34:45.269:INFO [watcher]: Changed file "/Users/menangen/WebStormProjects/game-vue-nodejs-site/browser/src/components/test.vue".
10 01 2017 19:34:56.501:INFO [watcher]: Changed file "/Users/menangen/WebStormProjects/game-vue-nodejs-site/browser/src/components/test.vue".
10 01 2017 19:35:12.729:INFO [watcher]: Changed file "/Users/menangen/WebStormProjects/game-vue-nodejs-site/browser/src/tests/global.spec.js".
```

On every this watcher's event I would start recompile _global.spec.js_.

**Comment by jlmakes** [comment]
Hey @menangen, this is the same issue described in detail [here](https://github.com/jlmakes/karma-rollup-preprocessor/issues/3#issuecomment-264055216).

The problem is that you are only passing `global.spec.js` to the rollup preprocessor, which means your other files (that you want to trigger a rebuild) aren't going through the preprocessor... and thus don't trigger anything.

I assume you'll need some type of `rollup-plugin-vue` added to the rollup plugins configuration, but you'll want to add the source files you want to trigger rebuilds to your preprocessor. Something like this:

```js
files: [
	'browser/src/tests/global.spec.js',
	{pattern: 'browser/src/components/*.vue', served: false, included: false}
],
preprocessors: {
	'browser/src/tests/global.spec.js': ['rollup'],
	'browser/src/components/*.vue': ['rollup']
},
```

**Karma Rollup Preprocessor** will be able to track dependents and dependencies for both your test _and_ the source files. This is exactly what version 3 made possible.

**Comment by menangen** [comment]
@jlmakes yes, it work but karma runs tests twice. First for changed .vue component and second for .spec.js main test file. If I change test file - it recompile .spec.js fast and once, if change only .vue component to broken code - karma runs 1st iteration with log about changes in .vue file and test show succes(!) pass, and on second iteration log write about changes in main .spec.js file - and now test fails. Very strange...

**Comment by jlmakes** [comment]
>"yes, it work but karma runs tests twice."

This is the exact problem I'm looking to solve with version 4. There's no way to programmatically add files to the preprocessor, so instead it has to trick Karma into rebundling them by changing their time modified.

As you've pointed out @menangen, this means the tests re-run for each file that depends on the changed file. There also seems to be some issues where tests can fail because files were changed mid-test...

All this is to say that the Karma watcher needs to be disabled, and the preprocessor needs to own the watch process (just like Webpack does).

**Comment by menangen** [comment]
@jlmakes ok, I dislike Webpack and will be better use browserify like rebuild as you can test  from https://github.com/vuejs-templates/browserify

Also if you on Mac, you can use my testing repo with karma-rollup-preprocessor and Vue building:

```sh
diskutil erasevolume HFS+ 'RAM Disk' `hdiutil attach -nomount ram://1000000` && cd /Volumes/RAM\ Disk/ && git clone --depth 1 https://github.com/menangen/game-vue-nodejs-site.git --branch tests --single-branch && cd game-vue-nodejs-site && npm install && node_modules/.bin/karma start
```
This shell command create RAM disk and clones my repo for playing with rollup + Karma. Also in _karma.conf.js_ need change ```autoWatch: false``` to ```autoWatch: true```, than working normal only when change .vue component, test runs nice, but on changing .spec.js test file - no restart Karma tests...

**Comment by FezVrasta** [comment]
Are there any progress on this issue? Thank you!

**Comment by jlmakes** [comment]
Hey @FezVrasta, thanks for the reminder there’s still work to be done here!

The documentation is all about how to use Karma, but developing plugins requires reverse engineering existing plugins. So, I’ve been looking deeper into the Node API and wrapping my head around how the Webpack plugin handles their custom file watcher...

This will be addressed, just bear with me a bit longer.

**Comment by elasim** [comment]
Sorry again, Any progress on this issue?

**Comment by jlmakes** [comment]
Not yet @elasim—I have not forgotten about this project—I use it every day and intend on improving it, I’ve just been busy the past 8 months working on another project.

What `karma-rollup-preprocessor` needs is a re-write using it’s own file watcher, so we can more closely control when files are re-processed (similar to how `karma-webpack` works).

**Comment by jlmakes** [comment]
Re: @FezVrasta @menangen @elasim 

I have greatly improved the file watcher in the latest major release (v5)!

Please take a careful look at:
- The [changes made in `karma-rollup-preprocessor@5.0.0`](https://github.com/jlmakes/karma-rollup-preprocessor/blob/master/CHANGELOG.md)
- The [changes made in `rollup@0.48`](https://gist.github.com/Rich-Harris/d472c50732dab03efeb37472b08a3f32)

The short version is this:

- The preprocessor no longer installs rollup for you (you manage what version you have installed)
- The preprocessor no longer works with Rollup v0.47 and below.
- You _will_ need to update both your Karma and Rollup configurations.

**Comment by mjeanroy** [comment]
@jlmakes Thanks for your awesome work!
