### ISSUE TITLE
Add possibility to define configuration with `customPreprocessors`

### ISSUE THREAD

**Issue by mjeanroy** [jlmakes/karma-rollup-preprocessor#19]
Hi @jlmakes ,

Currently, the only way to specify rollup configuration is with the `rollupPreprocessor`: easy, and enough for 99% use case.

But, it could be great to support configuration using `customPreprocessors` (documented [here](http://karma-runner.github.io/1.0/config/preprocessors.html), or you can see it implemented by `karma-babel-preprocessor`).

It could be a simple solution to provide different rollup configuration for specific files, for example:

```javascript
module.exports = (config) => {
  config.set({
    // Karma Configuration
    // ...

    preprocessors: {
      'test/index1.js': ['rollup'],
      'test/index2.js': ['rollupCustom'],
    },

    rollupPreprocessor: {
      // Default rollup configuration...
    },

    customPreprocessors: {
      rollupCustom: {
        base: 'rollup',
        // Custom rollup configuration for this file...
      },
    },
  });
});
```

I already made some tests on a project and I would be happy to open a PR for that, what do you think?

**Comment by jlmakes** [comment]
Thanks @mjeanroy I appreciate the contribution!

Next change I get, I’ll merge and prepare a `3.1.0` release.

**Comment by mjeanroy** [comment]
@jlmakes Ok, thank you! Let me know when `3.1.0` is available, this feature will make my life easier 😉

**Comment by jlmakes** [comment]
This is now in version `4.0.0` @mjeanroy.
