### ISSUE TITLE
bundle.generate returns a Promise 

### ISSUE THREAD

**Issue by jacmendt** [jlmakes/karma-rollup-preprocessor#22]
In my development environment `bundle.generate` returns a Promise. Because of this my karma preprocessing fails.

A short fix this can be seen here:

https://github.com/pikobytes/karma-rollup-preprocessor/blob/master/lib/index.js

If you want a i could provide a pull request.

I am using `rollup@^0.45.1`.

**Comment by mjeanroy** [comment]
@jacmendt See #21
