### ISSUE TITLE
bundle.generate(...) now returns a Promise instead of a { code, map } object

### ISSUE THREAD

**Issue by robhicks** [jlmakes/karma-rollup-preprocessor#23]
The buble example doesn't work for me. 

Here's part of my **karma.conf.js**:

```Javascript
preprocessors: {
	'src/**/test*.js': ['rollup']
},
reporters: ['spec'],
rollupPreprocessor: {
	plugins: [buble()],
	format: 'iife'
}
```

**Comment by jlmakes** [comment]
What version of rollup and preprocessor are you using?

**Comment by robhicks** [comment]
Thanks. I'll look at the PR you referenced. 

i'm using: 
- rollup 0.48.2
- karma-rolup-preprocessor 4.0.3

**Comment by jlmakes** [comment]
Hmm, those seem up to date. Can you share more about the problem?

**Comment by robhicks** [comment]
Sure, I removed and rebuilt node_modules. Now I'm seeing something different. Here's an example:
```shell
idx-admin-tab
    ✗ "before all" hook
	Error: Uncaught ReferenceError: process is not defined (dist/idx-admin-tab.js:609)
	    at Context.<anonymous> (src/idx-admin-tab/test.js:9:19)

    ✗ "after all" hook
	Error: Uncaught ReferenceError: process is not defined (dist/idx-admin-tab.js:609)
	    at Context.<anonymous> (src/idx-admin-tab/test.js:14:19)
```
process is not referenced in any of my tests.

**Comment by jlmakes** [comment]
There are some recent changes made to Rollup in 0.45 and now 0.48 that have caused a bit of turbulence for tools like this preprocessor—but none of that seems related to those error messages (which appeared recently after reinstalling node modules).

Is there a way to show this is related to karma-rollup-preprocessor?

**Comment by robhicks** [comment]
I found the issue. I was pre-building my distribution files with rollup and buble using nodeResolve. When nodeResolve is used, it injects process.env checks into the code. When running the tests, a type error was being thrown for process.
