### ISSUE TITLE
why do I need to explicitly config the plugins?

### ISSUE THREAD

**Issue by zzzgit** [jlmakes/karma-rollup-preprocessor#29]
![image](https://user-images.githubusercontent.com/1060733/31474564-32e76744-af2e-11e7-8730-30ff458c01c4.png)

![image](https://user-images.githubusercontent.com/1060733/31474601-6011a036-af2e-11e7-8401-7be063c209a7.png)

why do I need to explicitly config the plugins?

**Comment by mjeanroy** [comment]
Rollup is a peer-dependencies since version 5.0.0 (see #24), you now have to choose which version of rollup you want to use.

**Comment by brettz9** [comment]
Even with `rollup` as a devDep on my project, I'm getting this error. Any new info about this?
