### ISSUE TITLE
sourcemaps not working

### ISSUE THREAD

**Issue by AlbertoElias** [jlmakes/karma-rollup-preprocessor#33]
Using the latest versions, sourcemaps have stopped working. I updated my karma config with no success.

I'm using these versions:

```
"karma": "^2.0.0",
"karma-rollup-preprocessor": "^5.0.0",
"rollup": "^0.54.0"
```

And this config:

```js
rollupPreprocessor: {
	plugins: [...listOfPlugins],
	output: {
		sourcemap: 'inline'
	},
	format: 'iife',
	name: 'projectname'
}
```

Any suggestions?

**Comment by jlmakes** [comment]
Well, Rollup moved `opts.sourcemap` to `opts.output.sourcemap` in a recent release, but that was gently [patched](https://github.com/jlmakes/karma-rollup-preprocessor/commit/5cfd7e9e66afbfe67b37c9da8a8fc681d2409b64) in `5.1.1`. Still, it should work without the patch, you'll just get deprecation warnings.

I'm not sure what would cause source maps to stop being generated. I'm doing some poking around in one of my projects, but a simple repository demonstrating the issue would be ideal.

**Comment by AlbertoElias** [comment]
Ok, I don't have the code up just yet, but will do in 1-2 weeks. Do you mind if we leave this issue open until then?

**Comment by jlmakes** [comment]
That is fine, but please make sure the reproduction is a new repo, with only the code necessary to clearly reproduce the issue.

**Comment by Lalem001** [comment]
I have encountered this issue as well. So here is a repo that reproduces the issue:

https://github.com/Lalem001/karma-rollup-preprocessor-issue
