### ISSUE TITLE
Add support of array configs

### ISSUE THREAD

**Issue by kirill-konshin** [jlmakes/karma-rollup-preprocessor#34]
Currently if `rollup.config.js` will export an array of configs the preprocessor will fail with an error:

```
Unknown option found: 0, 1, 2, 3, 4, 5, 6.
```

I suspect it's because preprocessor is using older version of Rollup.

**Comment by jlmakes** [comment]
Apparently array config was added in `rollup@0.42` (June 2017) allowing Rollup to create builds in parallel. Personally, I've used this feature to output both ES and CommonJS modules from one config file.

Do you mind explaining why you need the preprocessor to bundle your files more than once?

**Comment by kirill-konshin** [comment]
Same reason, to build ES and non-ES versions.

**Comment by jlmakes** [comment]
But what is the purpose of passing multiple module formats to the Karma's test runner?

**Comment by jlmakes** [comment]
But what is the purpose of passing multiple module formats to the Karma test runner?

**Comment by kirill-konshin** [comment]
Honestly, this question never raised in my head :) I simply used the same config for build and tests. But it does make sense to reduce the number of things to be built for tests. I think a meaningful message should appear in this case, current error is a bit misleading.
