### ISSUE TITLE
Watching doesn't start when debugging

### ISSUE THREAD

**Issue by abaksha-sc** [jlmakes/karma-rollup-preprocessor#41]
I use the following config to run karma (to debug unit tests):
`karma start tests/config.js --auto-watch --no-single-run  --no-coverage --no-browsers`
And then I open `http://localhost:9876/debug.html` directly in browser to run tests.
In this case watching doesn't start, because event `run_start` does not dispatch.
It works when open `http://localhost:9876/` at first, but I would like to have a possibility to skip this step, because in most cases tab with `debug.html` is opened and I just refresh it.

Maybe need to start watching without event `run_start`?

**Comment by jlmakes** [comment]
Do you know which flag prevents the `run_start` event?

***

_Related:_

https://glebbahmutov.com/blog/debugging-karma-unit-tests/
http://karma-runner.github.io/3.0/dev/public-api.html

**Comment by abaksha-sc** [comment]
There are two flags in coupe prevent `run_start`: `--no-single-run --no-browsers`

1. Here is event fires when `config.noSingleRun`: 
https://github.com/karma-runner/karma/blob/bb022a7fa06042eb0d98ed72c75b74038128d9c0/lib/server.js#L311
But I use flag `--no-single-run`

2. And here are event fired when `capturedBrowsers` is not empty:
https://github.com/karma-runner/karma/blob/bb022a7fa06042eb0d98ed72c75b74038128d9c0/lib/executor.js#L30
https://github.com/karma-runner/karma/blob/bb022a7fa06042eb0d98ed72c75b74038128d9c0/lib/middleware/runner.js#L38

But I use flag `--no-browsers`.

Because of this event `run_start` doesn't fire when I open `debug.html` directly.
Event fires when I open `http://localhost:9876/`. But it is a redundant step for me (and my colleagues).

**Comment by abaksha-sc** [comment]
May be just change event `run_start` to `listening` ?
https://github.com/karma-runner/karma/blob/bb022a7fa06042eb0d98ed72c75b74038128d9c0/lib/server.js#L175

It dispatches when karma server is ready. I think it is a good point to start watching.

**Comment by jlmakes** [comment]
That seems like a reasonable solution. It would easy enough to swap in `listening` for `run_start`, but in your estimation, would this constitute a breaking change?
