### ISSUE TITLE
Missing options in examples

### ISSUE THREAD

**Issue by provegard** [jlmakes/karma-rollup-preprocessor#58]
I followed the structure in the example in the README:

```js
rollupPreprocessor: {
  plugins: [...],
  output: {
    ...
  },
},
```

However, none of the plugins I specified were invoked. When I added `options`, it started working:

```js
rollupPreprocessor: {
  options: {
    plugins: [...],
    output: {
      ...
    },
  },
},
```

Other preprocessors I use don't have `options`, so it was not immediately obvious to me what was missing.

**Comment by jlmakes** [comment]
As I understand it, the `options` property is a common convention for [preprocessors](https://karma-runner.github.io/4.0/config/preprocessors.html) to distinguish between first-party and third-party configuration. I think a good example is the [karma-typescript-preprocessor](https://github.com/sergeyt/karma-typescript-preprocessor/):

```js
typescriptPreprocessor: {
	options: {
		sourceMap: false,
		target: 'ES5',
		module: 'amd',
		// etc...
	},
	transformPath(path) {
		return path.replace(/\.ts$/, '.js');
	}
}
```
The `options` property takes an `object` containing options to pass to the TypeScript compiler (third-party configuration).

Whereas other properties, `transformPath` in this case are, are for `karma-typescript-preprocessor` (first-party configuration).

**Comment by jlmakes** [comment]
We can see in the source how `karma-rollup-preprocessor` is designed:

https://github.com/jlmakes/karma-rollup-preprocessor/blob/9332a90e144d48dd20871bdc7ef90a2bc39bb9de/lib/index.js#L19-L22

There is no expectation of an `options` property for normal preprocessor configurations… everything is simply passed along to Rollup (with exception to `input` and `cache` being handled for you).

However when creating [configured preprocessors](https://github.com/jlmakes/karma-rollup-preprocessor#configured-preprocessors), the `options` property _is used_ to distinguished between first and third party options as mentioned above.

**Comment by jlmakes** [comment]
We can see in the source how `karma-rollup-preprocessor` is designed:

https://github.com/jlmakes/karma-rollup-preprocessor/blob/9332a90e144d48dd20871bdc7ef90a2bc39bb9de/lib/index.js#L19-L22

There is no expectation of an `options` property for normal preprocessor configurations… everything is simply passed along to Rollup (with exception to `input` and `cache` being handled for you).

However when creating [configured preprocessors](https://github.com/jlmakes/karma-rollup-preprocessor#configured-preprocessors), the `options` property _is used_ to distinguished between first and third party options as mentioned above.

Maybe future releases should use an `options` property in all cases. It's worth exploring.

**Comment by jlmakes** [comment]
We can see in the source how `karma-rollup-preprocessor` is designed:

https://github.com/jlmakes/karma-rollup-preprocessor/blob/9332a90e144d48dd20871bdc7ef90a2bc39bb9de/lib/index.js#L19-L22

There is no expectation of an `options` property for normal preprocessor configurations… everything is simply passed along to Rollup (with exception to `input` and `cache` being handled for you).

However when creating [configured preprocessors](https://github.com/jlmakes/karma-rollup-preprocessor#configured-preprocessors), the `options` property _is used_ to distinguished between first and third party options as mentioned above.

> ...none of the plugins I specified were invoked. When I added `options`, it started working

It sounds like you were using a configured preprocessor. Otherwise, please share a reproduction.
