### ISSUE TITLE
@rollup/plugin-multi-entry broken by #54

### ISSUE THREAD

**Issue by Lalem001** [jlmakes/karma-rollup-preprocessor#62]
The changes introduced by #54 breaks builds that involve `@rollup/plugin-multi-entry`.

Specifically:

```javascript
/**
 * for processors that have alternate source file extensions,
 * make sure to use the output rollup file name
 */
const parsedPath = path.parse(file.path);
file.path = `${parsedPath.dir}/${result.fileName}`;
```

I believe applying [hasNullByte](https://github.com/jlmakes/karma-rollup-preprocessor/blob/master/lib/Watcher.js#L35-L37) to `result.facadeModuleId` would resolve the issue

```javascript
if (result.facadeModuleId && !hasNullByte(result.facadeModuleId)) {
  const parsedPath = path.parse(file.path);
  file.path = `${parsedPath.dir}/${result.fileName}`;
}
```

> facadeModuleId: string | null, // the id of a module that this chunk corresponds to

Thoughts?

**Comment by jlmakes** [comment]
Can you share a little more about how it breaks?

I'm curious what `@rollup/plugin-multi-entry` does to the `facadeModuleId`, I wasn't able to figure that out by looking at its source.

**Comment by Lalem001** [comment]
`@rollup/plugin-multi-entry` registers all the files that it processes under a virtual file with the name of `\0rollup:plugin-multi-entry:entry-point`. `facadeModuleId` was the only ID property I could find that maintains the null byte. The rest of the properties like `fileName` replace the null byte with an underscore.

However, I am just discovering that karma itself prevents `@rollup/plugin-multi-entry` from working as expected in a different way. The plugin is expecting a glob, but Karma is already expanding the glob to individual files. This observation appears to tread on #49.

Still, that doesn't change the fact that tests were passing with `karma-rollup-preprocessor` 7.0.0, and failing with 7.0.1 with the same rollup config.

Sorry for being brief, I am in a hurry atm. Can expand more later if still needed.

**Comment by jlmakes** [comment]
Just following up on this @Lalem001. I'd like to fix this, do you still think your suggestion `!hasNullByte()` is the best way forward?

**Comment by Lalem001** [comment]
The suggestion is a possible solution. Karma would never use that particular plugin correctly anyway, since it only sends Rollup (and the preprocessor) 1 file at a time. The solution might resolve problems with other plugins that have not yet been reported.

I will say however that this issue so far has been preventing me from being on latest `karma-rollup-preprocessor`, and the solution proposed does resolve the issue for me locally.

**Comment by jlmakes** [comment]
That makes sense. Well, it seems like a fair precaution to check for null bytes. I updated the `development` branch, does this look correct to you?

**Comment by Lalem001** [comment]
Yes it looks correct, and it works for me locally.
