### ISSUE TITLE
#69 breaks configs with output.file

### ISSUE THREAD

**Issue by kurkle** [jlmakes/karma-rollup-preprocessor#70]
> Error: You must set either "output.file" for a single-file build or "output.dir" when generating multiple chunks.

**Comment by jlmakes** [comment]
With what version of Rollup? Also, could you share what the `output` object actually looks like?

(Does this mean anything to you @ntkme?)

**Comment by ntkme** [comment]
We can set `output.dir` only when user did not explicit set `output.file` or `output.dir`. I'm preparing a PR.
